#!/usr/bin/env perl

use strict;
use warnings;

use v5.10.1;
use autodie;

use Dancer2 ':syntax';
use Wjournal;
use Getopt::Long qw/:config no_ignore_case bundling/;
use Carp;
use File::Basename qw/!dirname/;
use File::Copy;
use File::Path qw/make_path/;
use Image::Imlib2;

my %actions = (
    search   => \&search_uploads,
    list     => \&list_uploads,
    delete   => \&delete_upload,
    upload   => \&upload_new,
);

my %opts;
my ($login, $pwd, $uid) = getpwuid($<);
my $uploads = "uploads/${login}/";
my $outdir = config->{appdir} . "/public/${uploads}";

sub get_options {
    $opts{'env'} = 'production';
    $opts{'filetype'} = '';

    GetOptions(
        "e|env=s"              => \$opts{'env'},
        "u|upload"             => \$opts{'upload'},
        "l|list-filess"        => \$opts{'list'},
        "d|delete-file=s"      => \$opts{'delete'},
        "r|resize:i"           => \$opts{'resize'},
        "t|thumbnail:i"        => \$opts{'thumb'},
        "N|answer-no"          => \$opts{'no'},
        "Y|answer-yes"         => \$opts{'yes'},
        "h|help"               => \$opts{'help'},
    );

    if ($opts{'help'}) {
        pod2usage( { -verbose => 1} );
        exit(0);
    }

    (defined $opts{'thumb'}) && ($opts{'thumb'} == 0)  && ($opts{'thumb'}  = 140);
    (defined $opts{'resize'}) && ($opts{'resize'} == 0) && ($opts{'resize'} = 580);

    $opts{'action'} = $actions{'upload'};
    ( $opts{'list'} )     && ($opts{'action'} = $actions{'list'});
    ( $opts{'delete'} )   && ($opts{'action'} = $actions{'delete'});

    for ($opts{'env'}) {
        when (/^d/i) {
            $opts{'env'} = 'development';
        }
        when (/^t/i) {
            $opts{'env'} = 'testing';
        }
        when (/^s/i) {
            $opts{'env'} = 'staging';
        }
        default {
            $opts{'env'} = 'production';
        }
    }
}

sub ask {
    my ($question, $default) = @_;
    $default ||= 'n';

    print "${question} " .
    (($default =~ /^y/i)? '[Y/n]' : '[y/N]' ) .
    " ? ";

    if ($opts{'yes'}) {
        print "y\n";
        return 1;
    }
    elsif ($opts{'no'}) {
        print "n\n";
        return 0;
    }

    chomp(my $answer = <STDIN>);
    return 1 if (($answer =~ /^y/i) || ($default =~ /^y/i && (!$answer)));

    0;
}


sub overwrite {
    my ($filename) = @_;
    return 1 if !(-e $filename);
    ask("${filename} exists, overwrite");
}

sub upload_new {
    my @uploaded = ();
    my $img_save = sub {
        my ($img, $filename) = @_;
        return () if !overwrite("${outdir}/${filename}");
        $img->save("${outdir}/${filename}");
        chmod 0644, "${outdir}/${filename}";
        return config->{'www_root'} . $uploads . $filename;
    };

    for my $file (@_) {
        my ($basename, $ext) = basename($file) =~ /(.*)\.([^\.]*)/;
        $basename ||= basename($file);
        my $filename = "${basename}" . (($ext)? ".${ext}" : "");
        my $img = Image::Imlib2->load($file);

        if ($img) {
            if ($opts{'thumb'}) {
                my $thm = $img->create_scaled_image($opts{'thumb'}, 0);
                my $filename = "${basename}_thm" . (($ext)? ".${ext}" : "");
                push @uploaded, $img_save->($thm, $filename);
            }
            ($opts{'resize'}) && ($img = $img->create_scaled_image($opts{'resize'}, 0));
            push @uploaded, $img_save->($img, $filename);
        }
        else {
            next if !overwrite("${outdir}/${filename}");
            copy $file, "${outdir}/${filename}";
            chmod 0644, "${outdir}/${filename}";
            push @uploaded, config->{'www_root'} . $uploads . $filename;
        }
    }

    print "Files uploaded:\n", (join "\n", @uploaded), "\n" if (@uploaded);
}

get_options;
set environment => $opts{'env'};
make_path($outdir, { mode => 0771 });
$opts{'action'}(@ARGV);

